### PR TITLE
fixes duplicate entry issue

### LINKED ISSUE #70: Repeated inserts of the same migration
While the migrations themselves are only run once, it seems that the runMigration function indiscriminately saves the migration to the database _regardless of whether it was run_. This seems to be a bug to me.

I believe the fix to be the following (replacing the existing implementation of 'runMigration'):
```haskell
-- | Run the given migration. After successful completion, saves the migration to the database.
runMigration :: MonadIO m => MigrateBackend -> MigrateSettings -> Migration -> SqlPersistT m ()
runMigration backend settings@MigrateSettings{..} migration = do
  currVersion <- maybe (-1) id <$> getCurrVersion
  let latestVersion = getLatestVersion migration
  when (currVersion < latestVersion) $ do
    getMigration backend settings migration >>= mapM_ executeSql
    now <- liftIO getCurrentTime
    rawExecute "INSERT INTO persistent_migration(latestVersion, label, timestamp) VALUES (?, ?, ?)"
      [ PersistInt64 $ fromIntegral version
      , PersistText $ Text.pack $ fromMaybe (show version) $ versionToLabel version
      , PersistUTCTime now
      ]
```

Does this seem like an acceptable fix?

### PR DESCRIPTION
**Pull request by ProofOfKeags**
Fixes #70

### CODE REVIEW

File: src/Database/Persist/Migration/Core.hs [hunk 1]
```diff
@@ -147,14 +147,16 @@ validateMigration migration = do
...
-  now <- liftIO getCurrentTime
-  let version = getLatestVersion migration
-  rawExecute "INSERT INTO persistent_migration(version, label, timestamp) VALUES (?, ?, ?)"
-    [ PersistInt64 $ fromIntegral version
-    , PersistText $ Text.pack $ fromMaybe (show version) $ versionToLabel version
-    , PersistUTCTime now
-    ]
+  currVersion <- fromMaybe (-1) <$> getCurrVersion backend
+  let latestVersion = getLatestVersion migration
+  when (currVersion < latestVersion) $ do
```
Comment (brandonchinn178) [inline src/Database/Persist/Migration/Core.hs:152]: I'm not fond of the `-1` magic number. Can we change this to
```hs
currVersion <- getCurrVersion backend
let latestVersion = ...
case currVersion of
  Just version | version > latestVersion -> return ()
  _ -> do
    ...
```
?

**Review by brandonchinn178 — COMMENTED** [review]
Sorry this is so late! I don't know how I didn't see this before.

File: src/Database/Persist/Migration/Core.hs (hunk 1 above)
Comment (ProofOfKeags) [reply src/Database/Persist/Migration/Core.hs:152]: That is definitely the better approach. Wish I could tell you why I made the choice I made. But it's been a while. If you wanna make the change in line you can, otherwise I'll eventually get around to it.

Comment (ProofOfKeags) [reply src/Database/Persist/Migration/Core.hs]: fixed.

**Comment by brandonchinn178** [comment]
Thanks!
